### ISSUE TITLE
Missing dependency: `email_validator`

### ISSUE THREAD

**Issue by sokqa** [m1zukash1/flask-todo#1]
Hi, `email_validator` is missing from the `pip install` command.

Nice app by the way, thank you for sharing.

**Comment by sokqa** [comment]
Adding a screenshot (I tried to register with a malformed email address). It seems `email_validator` is a `wtforms` dependency so the bug is not in your code.
![2024-06-28_15-47_email](https://github.com/m1zukash1/flask-todo/assets/22755497/054d194d-e8c1-4556-93bf-fead43d5f6ac)

Running  `pip install email_validator` solved the issue for me.

**Comment by m1zukash1** [comment]
Thank you for bringing this to my attention!

I've added email-validator to the installation steps in the README.
